### ISSUE TITLE
Errors when running Gruntfile.js

### ISSUE THREAD

**Issue by ltfschoen** [aktowns/purescript-simple-dom#18]
I have performed the following commands to setup my local repo:
```
cabal install cabal-install
cabal install purescript
npm install
bower install
```
But when I run the following command to run the Grunt tasks I get the following errors:
```
grunt
```

![screen shot 2015-01-01 at 2 50 02 pm](https://cloud.githubusercontent.com/assets/6226175/5591620/d4505584-91c5-11e4-9d51-9bf33171183f.png)

And when I persist to run with force, it creates a .psci file in the main project directory, but I get these errors:
```
grunt --force
```

![screen shot 2015-01-01 at 2 53 26 pm](https://cloud.githubusercontent.com/assets/6226175/5591628/1459ff7c-91c6-11e4-93ee-0bb3d39133c0.png)

Contents of the .psci file that is created is 
```
:m src/Data/DOM/Simple/Ajax.purs
:m src/Data/DOM/Simple/Document.purs
:m src/Data/DOM/Simple/Element.purs
:m src/Data/DOM/Simple/Encode.purs
:m src/Data/DOM/Simple/Events.purs
:m src/Data/DOM/Simple/Navigator.purs
:m src/Data/DOM/Simple/Sugar.purs
:m src/Data/DOM/Simple/Types.purs
:m src/Data/DOM/Simple/Unsafe/Ajax.purs
:m src/Data/DOM/Simple/Unsafe/Document.purs
:m src/Data/DOM/Simple/Unsafe/Element.purs
:m src/Data/DOM/Simple/Unsafe/Events.purs
:m src/Data/DOM/Simple/Unsafe/Navigator.purs
:m src/Data/DOM/Simple/Unsafe/Sugar.purs
:m src/Data/DOM/Simple/Unsafe/Utils.purs
:m src/Data/DOM/Simple/Unsafe/Window.purs
:m src/Data/DOM/Simple/Window.purs
:m bower_components/purescript-arrays/src/Data/Array.purs
:m bower_components/purescript-arrays/src/Data/Array/ST.purs
:m bower_components/purescript-arrays/src/Data/Array/Unsafe.purs
:m bower_components/purescript-control/src/Control/Alt.purs
:m bower_components/purescript-control/src/Control/Alternative.purs
:m bower_components/purescript-control/src/Control/Apply.purs
:m bower_components/purescript-control/src/Control/Bind.purs
:m bower_components/purescript-control/src/Control/Comonad.purs
:m bower_components/purescript-control/src/Control/Extend.purs
:m bower_components/purescript-control/src/Control/Lazy.purs
:m bower_components/purescript-control/src/Control/Monad.purs
:m bower_components/purescript-control/src/Control/MonadPlus.purs
:m bower_components/purescript-control/src/Control/Plus.purs
:m bower_components/purescript-either/src/Data/Either.purs
:m bower_components/purescript-either/src/Data/Either/Nested.purs
:m bower_components/purescript-exceptions/src/Control/Monad/Eff/Exception.purs
:m bower_components/purescript-foldable-traversable/src/Data/Foldable.purs
:m bower_components/purescript-foldable-traversable/src/Data/Traversable.purs
:m bower_components/purescript-maps/src/Data/Map.purs
:m bower_components/purescript-maps/src/Data/StrMap.purs
:m bower_components/purescript-maps/src/Data/StrMap/ST.purs
:m bower_components/purescript-maps/src/Data/StrMap/ST/Unsafe.purs
:m bower_components/purescript-maps/src/Data/StrMap/Unsafe.purs
:m bower_components/purescript-math/src/Math.purs
:m bower_components/purescript-maybe/src/Data/Maybe.purs
:m bower_components/purescript-maybe/src/Data/Maybe/Unsafe.purs
:m bower_components/purescript-monoid/src/Data/Monoid.purs
:m bower_components/purescript-monoid/src/Data/Monoid/All.purs
:m bower_components/purescript-monoid/src/Data/Monoid/Any.purs
:m bower_components/purescript-monoid/src/Data/Monoid/Dual.purs
:m bower_components/purescript-monoid/src/Data/Monoid/Endo.purs
:m bower_components/purescript-monoid/src/Data/Monoid/First.purs
:m bower_components/purescript-monoid/src/Data/Monoid/Last.purs
:m bower_components/purescript-monoid/src/Data/Monoid/Product.purs
:m bower_components/purescript-monoid/src/Data/Monoid/Sum.purs
:m bower_components/purescript-quickcheck/src/Test/QuickCheck.purs
:m bower_components/purescript-quickcheck/src/Test/QuickCheck/Gen.purs
:m bower_components/purescript-random/src/Control/Monad/Eff/Random.purs
:m bower_components/purescript-sets/src/Data/Set.purs
:m bower_components/purescript-strings/src/Data/Char/Char.purs
:m bower_components/purescript-strings/src/Data/String.purs
:m bower_components/purescript-strings/src/Data/String/Regex.purs
:m bower_components/purescript-strings/src/Data/String/Unsafe.purs
:m bower_components/purescript-tuples/src/Data/Tuple.purs
```

I suspected that I was having these problems because I had NOT run the following (but I have been avoiding doing so because last time I ran 'cabal update' it broke GHC Haskell.
``` 
cabal update
```

Even when I run it, it keeps telling me to perform 'cabal install cabal-install', even when I already have:

![screen shot 2015-01-01 at 4 28 35 pm](https://cloud.githubusercontent.com/assets/6226175/5591716/4bd20dd4-91d3-11e4-84dc-f97988bcda4f.png)

Also, there is no executable for purescript in /usr/local/bin and /usr/local/bin/purescript does not exist, so running 'psc' or 'psci' at the command line responds with error that command is not found

I am currently using GHC version 7.8.3

Running the following returns nothing:
```
which purescript
```

**Comment by joneshf** [comment]
This sounds like you don't have your cabal-installed binaries on your path. If you try `cabal --version` I'll bet it doesn't say `1.2.0.6`. I forget what the default location for cabal binaries is but I thikn its `~/.cabal/bin`. See if the binaries are installed there. If so, there's your problem.

There are a few links around that describe what all is going on and the proper way to fix it. One good guide for setting up an environment is here: https://github.com/bitemyapp/learnhaskell#getting-started

So, this is not a problem of the library.

**Comment by joneshf** [comment]
Oh, another option is to use the releases https://github.com/purescript/purescript/releases just toss them in a directory that's on the path and you should be good to go.

**Comment by ltfschoen** [comment]
@joneshf Thanks it appears you're absolutely correct. Even though running ``` cabal install cabal-install ``` tells me that it has install Cabal-1.20.0.6, when I run the command ``` cabal --version ``` it tells me ``` cabal-install version 1.18.0.5 using version 1.18.1.4 of the Cabal library ```.
I found https://github.com/bitemyapp/learnhaskell#getting-started a very useful resource, including its advice about updating the ~/.bashrc... but I ended up following its link to [Detailed manual install guide for Mac OS X](https://github.com/bitemyapp/learnhaskell#detailed-manual-install-guide-for-mac-os-x), which has a heading called **tl;dr**, which got me back to square one, telling me to "Add ~/.cabal/bin/ to PATH", so I took a look in the ~/.cabal directory, and noticed the file where-is-my-stuff.txt, which I opened and found it contained the following:
```
=== Configuration for cabal has been written to
    /Users/Luke/.cabal/config

=== Executables will be installed in:
    /Users/Luke/Library/Haskell/bin

    You may wish to place this on your PATH by adding the following
    line to your ~/.bash_profile:

    export PATH="$HOME/Library/Haskell/bin:$PATH"
...
```
So I opened ~/.bash_profile to find it included the following line ``` export PATH="$HOME/.cabal/bin":$PATH ```(but that /bin extension doesn't exist), and then I added some extra lines, but this didn't make any difference: 
```
export PATH="$HOME/Library/Haskell/bin:$PATH"
alias cabal="$HOME/Library/Haskell/bin/cabal"
```

As a last resort, I went to [PureScript Releases](https://github.com/purescript/purescript/releases) and downloaded and extracted macos.tar.gz (PureScript v0.6.2) into the directory /Library/Haskell/bin/cabal, which creates the directory /Library/Haskell/bin/cabal/purescript, containing files, psc, psc-docs, psc-make, and psci

But even after doing this, running 'psc' still returns command not found, whilst running 'cabal update' always tells me there's a newer version of cabal-install available (even after I run 'cabal install cabal-install'), and running ``` cabal --version ``` still tells me ``` cabal-install version 1.18.0.5 using version 1.18.1.4 of the Cabal library ```

Any ideas?

**Comment by joneshf** [comment]
I'm not entirely sure why that didn't work. Did you try `source`-ing your `~/.bash_profile` file? I think at this point it's best to close this thread here and seek help from `#haskell` or `#haskell-beginners` on freenode, the haskell subreddit, or some other resources.

Also, the ps binaries just need to be on the path somewhere, `/Library/Haskell/bin/cabal/purescript` isn't on your path it seems.

**Comment by ltfschoen** [comment]
@joneshf Thanks for helping me get it all working, I don't recall ever manually having to reload my current shell before, but doing as you suggested with the following command did the trick!
```
source ~/.bash_profile
```
So now when I run ``` cabal --version``` it returns ``` cabal-install version 1.20.0.6
using version 1.20.0.3 of the Cabal library```
And most importantly, I can now run PureScript commands like ``` psc --help ``` :+1:
Now when I run ```grunt``` now, it executes and passes all the tests in /tests/Tests.purs successfully, except for the last one which tests the 'userAgent'. Even if I open Chrome Dev Tools, and type ``` self ``` to return the Window object, and then expand it (i.e. Window > clientInformation > userAgent), and then copy its value, which in my case is: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36", and then paste it in Test.purs (replacing the sample userAgent value), and then run ``` grunt ``` again, it still fails.... Do you know what could be causing this? (obviously I can get all the tests to pass if I just comment out the final userAgent test on Line 122, but i'm curious...)

Btw, I've written a blogpost about PureScript Simple DOM on my [Personal Blog here](http://lukeschoen.blogspot.com/)

![screen shot 2015-01-01 at 11 12 35 pm](https://cloud.githubusercontent.com/assets/6226175/5592143/1f7f6ff4-920c-11e4-8d72-73df04a362f1.png)
