### ISSUE TITLE
userAgent Test fails

### ISSUE THREAD

**Issue by ltfschoen** [aktowns/purescript-simple-dom#19]
When I run ```grunt```, it executes and passes all the tests in /tests/Tests.purs successfully, except for the last one which tests the 'userAgent' of the browser. 

Even if I open Chrome Dev Tools, and type ``` self ``` to return the Window object, and then expand it (i.e. Window > clientInformation > userAgent), and then copy its value, which in my case is: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36", and then paste it in Test.purs (replacing the sample userAgent value), and then run ``` grunt ``` again, it still fails.... 

Do you know what could be causing this? (obviously I can get all the tests to pass if I just comment out the final userAgent test on Line 122, but i'm curious...)

![screen shot 2015-01-01 at 11 12 35 pm](https://cloud.githubusercontent.com/assets/6226175/5592143/1f7f6ff4-920c-11e4-8d72-73df04a362f1.png)

**Comment by aktowns** [comment]
Should be fixed in @e40a4fae333b84f8f61ab49592e29e7da4ae7142 thanks :)
