### ISSUE TITLE
Absence of document.createElement()?

### ISSUE THREAD

**Issue by AKST** [aktowns/purescript-simple-dom#24]
Hey I'm just wondering if there's a particular reason there isn't equivalent of [document.createElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement) (At least I don't think there is?). Part of me thinks I may be trying to solve the wrong problem with the library, but then again this is part of the dom API, so I'm not sure. 

Thanks!

**Comment by puffnfresh** [comment]
Have wanted this a couple times :+1:
