### ISSUE TITLE
Absence of mouse down/up events

### ISSUE THREAD

**Issue by brendanfh** [aktowns/purescript-simple-dom#32]
I was going to use this library to create a HTML5 game in purescript; However, there is a lack of "mousedown" and "mouseup" events, so using the mouse for the game is rather tricky.

After looking though the code, I see that all that should have to be done is add these events to the `MouseEventType` in Events.purs. Should I make a pull request?

**Comment by sharkdp** [comment]
I have implemented them in my fork. You can find the corresponding commit here: https://github.com/sharkdp/purescript-simple-dom/commit/d2284cf4fa15a09e895206e7c85341135868149c

I could also send a pull request, if there is any interest.

**Comment by sharkdp** [comment]
This has been fixed now (d2284cf4fa15a09e895206e7c85341135868149c)
