### ISSUE TITLE
Please create a release

### ISSUE THREAD

**Issue by svisser** [aktowns/purescript-simple-dom#37]
I'm trying to use purescript-simple-dom#0.0.2 with other dependencies but the package depends on some older versions (e.g., purescript-arrays ~0.3.2). Would it be possible to create a release that includes [this commit][1] which would update those dependencies (to allow use of purescript-arrays#0.4.x)?

[1]: https://github.com/aktowns/purescript-simple-dom/commit/0887a276f81b02f6403cf740649157f78d4f9525

**Comment by aktowns** [comment]
Pushed a 0.0.3 tag :)

**Comment by svisser** [comment]
That's great - thanks for the quick response!
