### ISSUE TITLE
Doesn't compile with purescript 0.7.3

### ISSUE THREAD

**Issue by jutaro** [aktowns/purescript-simple-dom#42]
As orphan instances are now forbidden, the code has to restructured completely..

**Comment by garyb** [comment]
I think this should be fixable by shuffling the instance declarations around a bit, I can't really see a reason why it would require orphans currently.

**Comment by manpages** [comment]
What's the status of this issue?

Should I hop in and try to fix it, or is it wip already?

**Comment by jutaro** [comment]
I can't see any work on this and would be very happy if you can start the
port.


2015-08-20 17:42 GMT+02:00 Jonns Mostovoys <notifications@github.com>:

**Comment by manpages** [comment]
@jutaro et al, I request feedback on [this commit](https://github.com/serokell/purescript-simple-dom/commit/bcacb90689f1d1b6ba2c783e65e3734c12ca416b).

Hopefully, ADT-value interfaces aren't frowned upon by any of you and I can keep refactoring the library in that style.

Also, it's my fourth day of PureScripting, so I might have some non-idiomatic constructs, please proof-read.

**Comment by puffnfresh** [comment]
@manpages awesome stuff!

**Comment by aktowns** [comment]
fixed for 0.7.5 @ dc0caba5dc898b50b9ecb222d350b3e85e7f6044 tagged 1.3
