### ISSUE TITLE
Reomve Sugar module

### ISSUE THREAD

**Issue by manpages** [aktowns/purescript-simple-dom#46]
Is there any particular reason we want to have arrow-looking operators in this library?

Even as a sarcastic nod to some Haskell libraries I can't see how it's worth it.

Besides, arrows should point, not change and IIRC we had arrows in Sugar that mutated DOM.

Removal of ``Sugar`` module was already done in #44.

**Comment by aktowns** [comment]
removed in dc0caba5dc898b50b9ecb222d350b3e85e7f6044
